name: xoak
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - dask
  - dask-labextension
  - xarray
  - scikit-learn
  - jupyter
  - jupyterlab
  - notebook
  - ipykernel
  - matplotlib
  - sphinx
  - sphinx-autosummary-accessors
  - sphinx_rtd_theme
  - pip
  - pip:
      - git+https://github.com/ESM-VFC/xoak
