name: xoak
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scikit-learn
  - matplotlib
  - pip
  - pip:
      - ipykernel
      - dask
      - xarray
      - sphinx
      - sphinx-autosummary-accessors
      - sphinx_rtd_theme
      - nbsphinx
      - git+https://github.com/ESM-VFC/xoak
